ARG BASE_IMAGE=livepeer/ai-runner:live-apps
FROM ${BASE_IMAGE}

RUN pip install --no-cache-dir \
    git+https://github.com/pschroedl/segment-anything-2-real-time@notebook_test

# Copy application files
COPY app/ /app/app

CMD ["uvicorn", "app.main:app", "--log-config", "app/cfg/uvicorn_logging_config.json", "--host", "0.0.0.0", "--port", "8000"]
